RSS_SOURCES = [
    {
        "source_name": "EIA Today in Energy",
        "source_type": "rss",
        "base_url": "https://www.eia.gov",
        "feed_url": "https://www.eia.gov/rss/todayinenergy.xml",
        "domain_name": "eia.gov",
        "topic_focus": "energy,oil_market,supply,demand",
    },
    {
        "source_name": "EIA Press Releases",
        "source_type": "rss",
        "base_url": "https://www.eia.gov",
        "feed_url": "https://www.eia.gov/rss/press_rss.xml",
        "domain_name": "eia.gov",
        "topic_focus": "energy,oil_market,supply,demand",
    },
    {
        "source_name": "ECB Press Releases",
        "source_type": "rss",
        "base_url": "https://www.ecb.europa.eu",
        "feed_url": "https://www.ecb.europa.eu/rss/press.html",
        "domain_name": "ecb.europa.eu",
        "topic_focus": "economy,tariffs,sanctions,macro",
    },
    {
        "source_name": "ECB Blog",
        "source_type": "rss",
        "base_url": "https://www.ecb.europa.eu",
        "feed_url": "https://www.ecb.europa.eu/rss/blog.html",
        "domain_name": "ecb.europa.eu",
        "topic_focus": "economy,macro,policy",
    },
    {
        "source_name": "IMF News",
        "source_type": "rss",
        "base_url": "https://www.imf.org",
        "feed_url": "https://www.imf.org/en/news/rss",
        "domain_name": "imf.org",
        "topic_focus": "economy,macro,sanctions,tariffs,geopolitics",
    },

    # Added official sources below

    {
        "source_name": "Federal Reserve All Press Releases",
        "source_type": "rss",
        "base_url": "https://www.federalreserve.gov",
        "feed_url": "https://www.federalreserve.gov/feeds/press_all.xml",
        "domain_name": "federalreserve.gov",
        "topic_focus": "economy,macro,policy,interest_rates,financial_markets",
    },
    {
        "source_name": "Federal Reserve Monetary Policy",
        "source_type": "rss",
        "base_url": "https://www.federalreserve.gov",
        "feed_url": "https://www.federalreserve.gov/feeds/press_monetary.xml",
        "domain_name": "federalreserve.gov",
        "topic_focus": "economy,macro,policy,interest_rates,financial_markets",
    },
    {
        "source_name": "Federal Reserve Balance Sheet",
        "source_type": "rss",
        "base_url": "https://www.federalreserve.gov",
        "feed_url": "https://www.federalreserve.gov/feeds/clp.xml",
        "domain_name": "federalreserve.gov",
        "topic_focus": "economy,macro,liquidity,financial_markets,banking",
    },
    {
        "source_name": "EU Sanctions Guidance",
        "source_type": "rss",
        "base_url": "https://finance.ec.europa.eu",
        "feed_url": "https://finance.ec.europa.eu/node/1296/rss_en",
        "domain_name": "finance.ec.europa.eu",
        "topic_focus": "sanctions,tariffs,trade,geopolitics,energy",
    },
    {
        "source_name": "EU Sanctions FAQs",
        "source_type": "rss",
        "base_url": "https://finance.ec.europa.eu",
        "feed_url": "https://finance.ec.europa.eu/node/1068/rss_en",
        "domain_name": "finance.ec.europa.eu",
        "topic_focus": "sanctions,trade,geopolitics,energy,finance",
    },
    {
        "source_name": "EU Sanctions Energy FAQs",
        "source_type": "rss",
        "base_url": "https://finance.ec.europa.eu",
        "feed_url": "https://finance.ec.europa.eu/node/1068/rss_en?f%5B0%5D=sanctions_category_sanctions_category%3A154",
        "domain_name": "finance.ec.europa.eu",
        "topic_focus": "sanctions,energy,oil_market,geopolitics,trade",
    },
]